# Generated by Django 4.2.3 on 2023-07-27 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
