# Generated by Django 4.2.4 on 2023-08-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
    ]
