repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files


    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0

  - hooks:
      - always_run: true
        entry: python manage.py test
        id: django-test
        language: system
        name: django-test
        pass_filenames: false
    repo: local
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2


  - repo: https://github.com/wemake-services/dotenv-linter
    rev: 0.2.0  # Use the ref you want to point at
    hooks:
      - id: dotenv-linter
