repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.10.0
- hooks:
  - id: ruff
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.275
- hooks:
  - always_run: true
    entry: python manage.py test
    id: django-test
    language: system
    name: django-test
    pass_filenames: false
  repo: local
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.5.2
